name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 設置 Node.js 環境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      # 安裝依賴
      - name: Install dependencies
        run: npm install

      # 編譯並靜態導出 Next.js
      - name: Build Next.js
        run: npm run build

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages    
          cname: "ghp.imych.one"
